"""Adapter generator for JsonUI tests.

Generates adapter files that allow custom actions/configurations in tests.
"""

from pathlib import Path
from typing import Optional
import json

SUPPORTED_PLATFORMS = ["ios", "android", "web"]


def generate_adapter(
    platform: str,
    output_dir: Path,
    project_name: str = "MyApp",
    custom_actions: Optional[list[dict]] = None
) -> dict[str, Path]:
    """Generate adapter files for a platform.

    Args:
        platform: Target platform (ios, android, web)
        output_dir: Output directory for generated files
        project_name: Project name for namespacing
        custom_actions: Optional list of custom action definitions

    Returns:
        Dictionary of generated file paths
    """
    if platform not in SUPPORTED_PLATFORMS:
        raise ValueError(f"Unsupported platform: {platform}. Supported: {SUPPORTED_PLATFORMS}")

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated_files = {}

    if platform == "ios":
        generated_files = _generate_ios_adapter(output_dir, project_name, custom_actions)
    elif platform == "android":
        generated_files = _generate_android_adapter(output_dir, project_name, custom_actions)
    elif platform == "web":
        generated_files = _generate_web_adapter(output_dir, project_name, custom_actions)

    # Generate custom schema
    schema_path = output_dir / "jsonui-test-custom.schema.json"
    _generate_custom_schema(schema_path, custom_actions)
    generated_files["schema"] = schema_path

    return generated_files


def _generate_ios_adapter(
    output_dir: Path,
    project_name: str,
    custom_actions: Optional[list[dict]] = None
) -> dict[str, Path]:
    """Generate iOS adapter files."""
    adapter_path = output_dir / "JsonUITestAdapter.swift"

    # Build custom action cases
    custom_action_cases = ""
    custom_action_methods = ""
    if custom_actions:
        for action in custom_actions:
            name = action.get("name", "")
            desc = action.get("description", "")
            params = action.get("params", [])

            custom_action_cases += f'''
            case "{name}":
                // {desc}
                handle_{_to_snake_case(name)}(params: params)
'''
            param_doc = ", ".join([f"{p['name']}: {p.get('type', 'Any')}" for p in params])
            custom_action_methods += f'''
    /// {desc}
    /// Params: {param_doc if param_doc else "none"}
    private func handle_{_to_snake_case(name)}(params: [String: Any]) {{
        // TODO: Implement custom action
        print("[JsonUITestAdapter] {name} called with params: \\(params)")
    }}
'''

    content = f'''//
//  JsonUITestAdapter.swift
//  {project_name}UITests
//
//  Auto-generated by jsonui-test
//  Customize this file to add your own test configurations and actions.
//

import XCTest

/// Protocol for JsonUI test adapter
/// Implement this in your UI test target to handle custom actions and configurations
protocol JsonUITestAdapterProtocol {{
    /// Configure test environment before launch
    func configure(settings: [String: Any], app: XCUIApplication)

    /// Execute a custom action during test
    func executeCustomAction(name: String, params: [String: Any], app: XCUIApplication) -> Bool
}}

/// Default implementation of JsonUI test adapter
/// Edit this class to add your custom configurations and actions
class JsonUITestAdapter: JsonUITestAdapterProtocol {{

    // MARK: - Singleton
    static let shared = JsonUITestAdapter()
    private init() {{}}

    // MARK: - Configuration

    /// Configure test environment based on settings from test JSON
    ///
    /// Example test JSON:
    /// ```json
    /// {{
    ///   "setup": [
    ///     {{ "action": "config", "settings": {{ "mock-iap": true, "skip-tutorial": true }} }}
    ///   ]
    /// }}
    /// ```
    func configure(settings: [String: Any], app: XCUIApplication) {{
        // Add launch arguments based on settings
        for (key, value) in settings {{
            switch key {{
            case "mock-iap":
                if value as? Bool == true {{
                    app.launchArguments.append("--mock-iap")
                }}

            case "mock-network":
                if value as? Bool == true {{
                    app.launchArguments.append("--mock-network")
                }}

            case "skip-tutorial":
                if value as? Bool == true {{
                    app.launchArguments.append("--skip-tutorial")
                }}

            case "reset-state":
                if value as? Bool == true {{
                    app.launchArguments.append("--reset-state")
                }}

            case "api-base-url":
                if let url = value as? String {{
                    app.launchEnvironment["API_BASE_URL"] = url
                }}

            case "test-user":
                if let userId = value as? String {{
                    app.launchEnvironment["TEST_USER_ID"] = userId
                }}

            default:
                // Generic handling: convert to launch argument
                if let boolValue = value as? Bool, boolValue {{
                    app.launchArguments.append("--\\(key)")
                }} else if let stringValue = value as? String {{
                    app.launchEnvironment[key.uppercased().replacingOccurrences(of: "-", with: "_")] = stringValue
                }}
            }}
        }}
    }}

    // MARK: - Custom Actions

    /// Execute a custom action
    ///
    /// Example test JSON:
    /// ```json
    /// {{
    ///   "steps": [
    ///     {{ "action": "custom", "name": "login-as-test-user", "params": {{ "userId": "test123" }} }}
    ///   ]
    /// }}
    /// ```
    ///
    /// - Returns: true if action was handled, false otherwise
    func executeCustomAction(name: String, params: [String: Any], app: XCUIApplication) -> Bool {{
        switch name {{
        case "login-as-test-user":
            // Example: Quick login as test user
            handleLoginAsTestUser(params: params, app: app)
            return true

        case "reset-database":
            // Example: Reset local database
            handleResetDatabase(params: params, app: app)
            return true

        case "set-feature-flag":
            // Example: Set a feature flag
            handleSetFeatureFlag(params: params, app: app)
            return true
{custom_action_cases}
        default:
            print("[JsonUITestAdapter] Unknown custom action: \\(name)")
            return false
        }}
    }}

    // MARK: - Custom Action Handlers

    private func handleLoginAsTestUser(params: [String: Any], app: XCUIApplication) {{
        guard let userId = params["userId"] as? String else {{
            print("[JsonUITestAdapter] login-as-test-user requires 'userId' param")
            return
        }}
        // TODO: Implement login logic
        // Example: Set environment variable for app to auto-login
        app.launchEnvironment["AUTO_LOGIN_USER_ID"] = userId
        print("[JsonUITestAdapter] Set up auto-login for user: \\(userId)")
    }}

    private func handleResetDatabase(params: [String: Any], app: XCUIApplication) {{
        // TODO: Implement database reset
        // Example: Call app's reset endpoint or clear UserDefaults
        app.launchArguments.append("--reset-database")
        print("[JsonUITestAdapter] Database reset requested")
    }}

    private func handleSetFeatureFlag(params: [String: Any], app: XCUIApplication) {{
        guard let flagName = params["name"] as? String,
              let flagValue = params["value"] else {{
            print("[JsonUITestAdapter] set-feature-flag requires 'name' and 'value' params")
            return
        }}
        // TODO: Implement feature flag setting
        app.launchEnvironment["FEATURE_\\(flagName.uppercased())"] = "\\(flagValue)"
        print("[JsonUITestAdapter] Set feature flag \\(flagName) = \\(flagValue)")
    }}
{custom_action_methods}
}}

// MARK: - Extension for XCTestCase

extension XCTestCase {{
    /// Apply JsonUI test configuration to app before launch
    func applyJsonUIConfig(_ settings: [String: Any], to app: XCUIApplication) {{
        JsonUITestAdapter.shared.configure(settings: settings, app: app)
    }}

    /// Execute a JsonUI custom action
    @discardableResult
    func executeJsonUIAction(_ name: String, params: [String: Any], app: XCUIApplication) -> Bool {{
        return JsonUITestAdapter.shared.executeCustomAction(name: name, params: params, app: app)
    }}
}}
'''

    with open(adapter_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return {"adapter": adapter_path}


def _generate_android_adapter(
    output_dir: Path,
    project_name: str,
    custom_actions: Optional[list[dict]] = None
) -> dict[str, Path]:
    """Generate Android adapter files."""
    adapter_path = output_dir / "JsonUITestAdapter.kt"

    # Build custom action cases
    custom_action_cases = ""
    custom_action_methods = ""
    if custom_actions:
        for action in custom_actions:
            name = action.get("name", "")
            desc = action.get("description", "")
            params = action.get("params", [])

            custom_action_cases += f'''
            "{name}" -> {{
                // {desc}
                handle{_to_pascal_case(name)}(params)
                true
            }}
'''
            param_doc = ", ".join([f"{p['name']}: {p.get('type', 'Any')}" for p in params])
            custom_action_methods += f'''
    /**
     * {desc}
     * Params: {param_doc if param_doc else "none"}
     */
    private fun handle{_to_pascal_case(name)}(params: Map<String, Any?>) {{
        // TODO: Implement custom action
        Log.d(TAG, "{name} called with params: $params")
    }}
'''

    content = f'''package com.{project_name.lower()}.test

import android.content.Intent
import android.util.Log
import androidx.test.core.app.ActivityScenario
import androidx.test.platform.app.InstrumentationRegistry

/**
 * JsonUI Test Adapter for Android
 *
 * Auto-generated by jsonui-test
 * Customize this file to add your own test configurations and actions.
 */
object JsonUITestAdapter {{

    private const val TAG = "JsonUITestAdapter"

    /**
     * Configure test environment before activity launch
     *
     * Example test JSON:
     * ```json
     * {{
     *   "setup": [
     *     {{ "action": "config", "settings": {{ "mock-iap": true, "skip-tutorial": true }} }}
     *   ]
     * }}
     * ```
     */
    fun configure(settings: Map<String, Any?>, intent: Intent) {{
        settings.forEach {{ (key, value) ->
            when (key) {{
                "mock-iap" -> {{
                    if (value == true) {{
                        intent.putExtra("MOCK_IAP", true)
                    }}
                }}

                "mock-network" -> {{
                    if (value == true) {{
                        intent.putExtra("MOCK_NETWORK", true)
                    }}
                }}

                "skip-tutorial" -> {{
                    if (value == true) {{
                        intent.putExtra("SKIP_TUTORIAL", true)
                    }}
                }}

                "reset-state" -> {{
                    if (value == true) {{
                        intent.putExtra("RESET_STATE", true)
                    }}
                }}

                "api-base-url" -> {{
                    (value as? String)?.let {{
                        intent.putExtra("API_BASE_URL", it)
                    }}
                }}

                "test-user" -> {{
                    (value as? String)?.let {{
                        intent.putExtra("TEST_USER_ID", it)
                    }}
                }}

                else -> {{
                    // Generic handling
                    when (value) {{
                        is Boolean -> intent.putExtra(key.uppercase().replace("-", "_"), value)
                        is String -> intent.putExtra(key.uppercase().replace("-", "_"), value)
                        is Int -> intent.putExtra(key.uppercase().replace("-", "_"), value)
                    }}
                }}
            }}
        }}
    }}

    /**
     * Execute a custom action
     *
     * Example test JSON:
     * ```json
     * {{
     *   "steps": [
     *     {{ "action": "custom", "name": "login-as-test-user", "params": {{ "userId": "test123" }} }}
     *   ]
     * }}
     * ```
     *
     * @return true if action was handled, false otherwise
     */
    fun executeCustomAction(name: String, params: Map<String, Any?>): Boolean {{
        return when (name) {{
            "login-as-test-user" -> {{
                handleLoginAsTestUser(params)
                true
            }}

            "reset-database" -> {{
                handleResetDatabase(params)
                true
            }}

            "set-feature-flag" -> {{
                handleSetFeatureFlag(params)
                true
            }}
{custom_action_cases}
            else -> {{
                Log.w(TAG, "Unknown custom action: $name")
                false
            }}
        }}
    }}

    // MARK: - Custom Action Handlers

    private fun handleLoginAsTestUser(params: Map<String, Any?>) {{
        val userId = params["userId"] as? String
        if (userId == null) {{
            Log.e(TAG, "login-as-test-user requires 'userId' param")
            return
        }}
        // TODO: Implement login logic
        // Example: Store in SharedPreferences for app to auto-login
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        context.getSharedPreferences("test_config", 0)
            .edit()
            .putString("AUTO_LOGIN_USER_ID", userId)
            .apply()
        Log.d(TAG, "Set up auto-login for user: $userId")
    }}

    private fun handleResetDatabase(params: Map<String, Any?>) {{
        // TODO: Implement database reset
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        // Example: Clear app data or call reset API
        Log.d(TAG, "Database reset requested")
    }}

    private fun handleSetFeatureFlag(params: Map<String, Any?>) {{
        val flagName = params["name"] as? String
        val flagValue = params["value"]
        if (flagName == null || flagValue == null) {{
            Log.e(TAG, "set-feature-flag requires 'name' and 'value' params")
            return
        }}
        // TODO: Implement feature flag setting
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        context.getSharedPreferences("feature_flags", 0)
            .edit()
            .putString(flagName, flagValue.toString())
            .apply()
        Log.d(TAG, "Set feature flag $flagName = $flagValue")
    }}
{custom_action_methods}
}}
'''

    with open(adapter_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return {"adapter": adapter_path}


def _generate_web_adapter(
    output_dir: Path,
    project_name: str,
    custom_actions: Optional[list[dict]] = None
) -> dict[str, Path]:
    """Generate Web (TypeScript) adapter files."""
    adapter_path = output_dir / "jsonui-test-adapter.ts"

    # Build custom action cases
    custom_action_cases = ""
    custom_action_methods = ""
    if custom_actions:
        for action in custom_actions:
            name = action.get("name", "")
            desc = action.get("description", "")
            params = action.get("params", [])

            custom_action_cases += f'''
      case '{name}':
        // {desc}
        await this.handle{_to_pascal_case(name)}(params);
        return true;
'''
            param_types = ", ".join([f"{p['name']}: {_js_type(p.get('type', 'any'))}" for p in params])
            custom_action_methods += f'''
  /**
   * {desc}
   */
  private async handle{_to_pascal_case(name)}(params: Record<string, unknown>): Promise<void> {{
    // TODO: Implement custom action
    console.log('[JsonUITestAdapter] {name} called with params:', params);
  }}
'''

    content = f'''/**
 * JsonUI Test Adapter for Web (Playwright/Cypress)
 *
 * Auto-generated by jsonui-test
 * Customize this file to add your own test configurations and actions.
 */

import type {{ Page, BrowserContext }} from '@playwright/test';

export interface JsonUITestConfig {{
  'mock-iap'?: boolean;
  'mock-network'?: boolean;
  'skip-tutorial'?: boolean;
  'reset-state'?: boolean;
  'api-base-url'?: string;
  'test-user'?: string;
  [key: string]: unknown;
}}

export interface CustomActionParams {{
  [key: string]: unknown;
}}

/**
 * JsonUI Test Adapter
 *
 * Usage:
 * ```typescript
 * const adapter = new JsonUITestAdapter(page, context);
 * await adapter.configure({{ 'mock-iap': true, 'skip-tutorial': true }});
 * await adapter.executeCustomAction('login-as-test-user', {{ userId: 'test123' }});
 * ```
 */
export class JsonUITestAdapter {{
  private page: Page;
  private context: BrowserContext;

  constructor(page: Page, context: BrowserContext) {{
    this.page = page;
    this.context = context;
  }}

  /**
   * Configure test environment
   *
   * Example test JSON:
   * ```json
   * {{
   *   "setup": [
   *     {{ "action": "config", "settings": {{ "mock-iap": true, "skip-tutorial": true }} }}
   *   ]
   * }}
   * ```
   */
  async configure(settings: JsonUITestConfig): Promise<void> {{
    for (const [key, value] of Object.entries(settings)) {{
      switch (key) {{
        case 'mock-iap':
          if (value === true) {{
            await this.page.evaluate(() => {{
              localStorage.setItem('MOCK_IAP', 'true');
            }});
          }}
          break;

        case 'mock-network':
          if (value === true) {{
            await this.page.evaluate(() => {{
              localStorage.setItem('MOCK_NETWORK', 'true');
            }});
          }}
          break;

        case 'skip-tutorial':
          if (value === true) {{
            await this.page.evaluate(() => {{
              localStorage.setItem('SKIP_TUTORIAL', 'true');
            }});
          }}
          break;

        case 'reset-state':
          if (value === true) {{
            await this.page.evaluate(() => {{
              localStorage.clear();
              sessionStorage.clear();
            }});
          }}
          break;

        case 'api-base-url':
          if (typeof value === 'string') {{
            await this.page.evaluate((url) => {{
              localStorage.setItem('API_BASE_URL', url);
            }}, value);
          }}
          break;

        case 'test-user':
          if (typeof value === 'string') {{
            await this.page.evaluate((userId) => {{
              localStorage.setItem('TEST_USER_ID', userId);
            }}, value);
          }}
          break;

        default:
          // Generic handling
          if (typeof value === 'boolean' && value) {{
            await this.page.evaluate((k) => {{
              localStorage.setItem(k.toUpperCase().replace(/-/g, '_'), 'true');
            }}, key);
          }} else if (typeof value === 'string') {{
            await this.page.evaluate(({{ k, v }}) => {{
              localStorage.setItem(k.toUpperCase().replace(/-/g, '_'), v);
            }}, {{ k: key, v: value }});
          }}
          break;
      }}
    }}
  }}

  /**
   * Execute a custom action
   *
   * Example test JSON:
   * ```json
   * {{
   *   "steps": [
   *     {{ "action": "custom", "name": "login-as-test-user", "params": {{ "userId": "test123" }} }}
   *   ]
   * }}
   * ```
   *
   * @returns true if action was handled, false otherwise
   */
  async executeCustomAction(name: string, params: CustomActionParams): Promise<boolean> {{
    switch (name) {{
      case 'login-as-test-user':
        await this.handleLoginAsTestUser(params);
        return true;

      case 'reset-database':
        await this.handleResetDatabase(params);
        return true;

      case 'set-feature-flag':
        await this.handleSetFeatureFlag(params);
        return true;
{custom_action_cases}
      default:
        console.warn(`[JsonUITestAdapter] Unknown custom action: ${{name}}`);
        return false;
    }}
  }}

  // Custom Action Handlers

  private async handleLoginAsTestUser(params: CustomActionParams): Promise<void> {{
    const userId = params.userId as string | undefined;
    if (!userId) {{
      console.error('[JsonUITestAdapter] login-as-test-user requires "userId" param');
      return;
    }}
    // TODO: Implement login logic
    // Example: Set localStorage for app to auto-login
    await this.page.evaluate((id) => {{
      localStorage.setItem('AUTO_LOGIN_USER_ID', id);
    }}, userId);
    console.log(`[JsonUITestAdapter] Set up auto-login for user: ${{userId}}`);
  }}

  private async handleResetDatabase(params: CustomActionParams): Promise<void> {{
    // TODO: Implement database reset
    // Example: Call API endpoint or clear IndexedDB
    await this.page.evaluate(() => {{
      indexedDB.deleteDatabase('app-database');
    }});
    console.log('[JsonUITestAdapter] Database reset requested');
  }}

  private async handleSetFeatureFlag(params: CustomActionParams): Promise<void> {{
    const flagName = params.name as string | undefined;
    const flagValue = params.value;
    if (!flagName || flagValue === undefined) {{
      console.error('[JsonUITestAdapter] set-feature-flag requires "name" and "value" params');
      return;
    }}
    // TODO: Implement feature flag setting
    await this.page.evaluate(({{ name, value }}) => {{
      localStorage.setItem(`FEATURE_${{name.toUpperCase()}}`, String(value));
    }}, {{ name: flagName, value: flagValue }});
    console.log(`[JsonUITestAdapter] Set feature flag ${{flagName}} = ${{flagValue}}`);
  }}
{custom_action_methods}
}}

// Export singleton factory
let adapterInstance: JsonUITestAdapter | null = null;

export function getJsonUITestAdapter(page: Page, context: BrowserContext): JsonUITestAdapter {{
  if (!adapterInstance) {{
    adapterInstance = new JsonUITestAdapter(page, context);
  }}
  return adapterInstance;
}}
'''

    with open(adapter_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return {"adapter": adapter_path}


def _generate_custom_schema(
    schema_path: Path,
    custom_actions: Optional[list[dict]] = None
) -> None:
    """Generate custom JSON schema for validation."""

    # Build custom action definitions
    custom_action_defs = []
    if custom_actions:
        for action in custom_actions:
            name = action.get("name", "")
            desc = action.get("description", "")
            params = action.get("params", [])

            param_properties = {}
            required_params = []
            for param in params:
                param_name = param.get("name", "")
                param_type = param.get("type", "string")
                param_desc = param.get("description", "")
                param_required = param.get("required", False)

                param_properties[param_name] = {
                    "type": _json_schema_type(param_type),
                    "description": param_desc
                }
                if param_required:
                    required_params.append(param_name)

            custom_action_defs.append({
                "name": name,
                "description": desc,
                "params": param_properties,
                "required": required_params
            })

    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "jsonui-test-custom.schema.json",
        "title": "JsonUI Test Custom Schema",
        "description": "Custom actions and configurations for JsonUI tests",
        "definitions": {
            "customAction": {
                "type": "object",
                "properties": {
                    "action": {"const": "custom"},
                    "name": {
                        "type": "string",
                        "description": "Custom action name",
                        "enum": [a["name"] for a in custom_action_defs] if custom_action_defs else None
                    },
                    "params": {
                        "type": "object",
                        "description": "Custom action parameters"
                    }
                },
                "required": ["action", "name"]
            },
            "configAction": {
                "type": "object",
                "properties": {
                    "action": {"const": "config"},
                    "settings": {
                        "type": "object",
                        "description": "Configuration settings",
                        "properties": {
                            "mock-iap": {"type": "boolean", "description": "Enable IAP mocking"},
                            "mock-network": {"type": "boolean", "description": "Enable network mocking"},
                            "skip-tutorial": {"type": "boolean", "description": "Skip tutorial screens"},
                            "reset-state": {"type": "boolean", "description": "Reset app state"},
                            "api-base-url": {"type": "string", "description": "Override API base URL"},
                            "test-user": {"type": "string", "description": "Test user ID for auto-login"}
                        },
                        "additionalProperties": True
                    }
                },
                "required": ["action", "settings"]
            },
            "customActions": {
                "type": "array",
                "items": custom_action_defs
            }
        },
        "customActions": custom_action_defs
    }

    # Remove None values
    if schema["definitions"]["customAction"]["properties"]["name"]["enum"] is None:
        del schema["definitions"]["customAction"]["properties"]["name"]["enum"]

    with open(schema_path, 'w', encoding='utf-8') as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)


def _to_snake_case(name: str) -> str:
    """Convert kebab-case or camelCase to snake_case."""
    result = name.replace("-", "_")
    # Convert camelCase
    import re
    result = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', result)
    result = re.sub('([a-z0-9])([A-Z])', r'\1_\2', result).lower()
    return result


def _to_pascal_case(name: str) -> str:
    """Convert kebab-case or snake_case to PascalCase."""
    words = name.replace("-", "_").split("_")
    return "".join(word.capitalize() for word in words)


def _js_type(type_str: str) -> str:
    """Convert type string to TypeScript type."""
    type_map = {
        "string": "string",
        "int": "number",
        "integer": "number",
        "float": "number",
        "number": "number",
        "bool": "boolean",
        "boolean": "boolean",
        "any": "unknown"
    }
    return type_map.get(type_str.lower(), "unknown")


def _json_schema_type(type_str: str) -> str:
    """Convert type string to JSON Schema type."""
    type_map = {
        "string": "string",
        "int": "integer",
        "integer": "integer",
        "float": "number",
        "number": "number",
        "bool": "boolean",
        "boolean": "boolean",
        "any": "string"  # Default to string for JSON schema
    }
    return type_map.get(type_str.lower(), "string")
